@extends('layouts.app')

@section('eyebrow', 'Student')
@section('heading', 'Internship Report')

@push('styles')
<style>
    @media print {
        aside, header, footer, .no-print { display: none !important; }
        main { padding: 0 !important; }
        body { background: white !important; }
    }
</style>
@endpush

@section('content')
    <div class="flex justify-end mb-4 no-print">
        <button onclick="window.print()" class="bg-ink text-white text-sm font-medium px-5 py-2.5 rounded-xl hover:bg-ink-soft transition">
            <i class="fa-solid fa-print mr-1.5"></i> Print / Save as PDF
        </button>
    </div>

    <div class="bg-white rounded-2xl border border-line p-10 max-w-4xl mx-auto">
        <div class="flex items-center justify-between border-b border-line pb-6 mb-8">
            <div>
                <p class="text-[11px] uppercase tracking-widest text-ink/40 font-mono mb-1">Internship Completion Report</p>
                <h2 class="font-display text-2xl font-semibold">{{ $student->user->name }}</h2>
                <p class="text-sm text-ink/50">{{ $student->student_no }} &middot; {{ $student->department }} &middot; {{ $student->program }}</p>
            </div>
            <div class="w-12 h-12 rounded-lg bg-ink flex items-center justify-center text-accent font-display font-bold">IT</div>
        </div>

        <div class="grid sm:grid-cols-2 gap-6 mb-8">
            <div>
                <p class="text-xs uppercase tracking-widest text-ink/40 font-mono mb-2">Internship</p>
                <p class="font-medium">{{ $internship->title }}</p>
                <p class="text-sm text-ink/60">{{ $internship->company_name }}</p>
                <p class="text-sm text-ink/50 mt-1">{{ $internship->start_date->format('d M Y') }} &ndash; {{ $internship->end_date->format('d M Y') }}</p>
            </div>
            <div>
                <p class="text-xs uppercase tracking-widest text-ink/40 font-mono mb-2">Supervisor</p>
                <p class="font-medium">{{ $student->supervisor?->user?->name ?? 'Not assigned' }}</p>
                <p class="text-sm text-ink/60">{{ $student->supervisor?->designation }} &middot; {{ $student->supervisor?->company_name }}</p>
            </div>
        </div>

        <div class="grid grid-cols-3 gap-4 mb-10">
            <div class="rounded-xl bg-canvas p-4 text-center">
                <p class="font-display text-2xl font-semibold">{{ $logs->count() }}</p>
                <p class="text-xs text-ink/50 mt-1">Log entries</p>
            </div>
            <div class="rounded-xl bg-canvas p-4 text-center">
                <p class="font-display text-2xl font-semibold">{{ number_format($logs->sum('hours_spent'), 1) }}</p>
                <p class="text-xs text-ink/50 mt-1">Total hours</p>
            </div>
            <div class="rounded-xl bg-canvas p-4 text-center">
                <p class="font-display text-2xl font-semibold">{{ $evaluation?->overall_rating ?? '—' }}</p>
                <p class="text-xs text-ink/50 mt-1">Overall rating</p>
            </div>
        </div>

        <p class="text-xs uppercase tracking-widest text-ink/40 font-mono mb-4">Logbook summary</p>
        <div class="space-y-3 mb-10">
            @foreach ($logs as $log)
                <div class="flex items-start gap-4 text-sm border-b border-line pb-3">
                    <span class="font-mono text-ink/40 w-20 flex-shrink-0">{{ $log->log_date->format('d M Y') }}</span>
                    <span class="flex-1">{{ $log->title }}</span>
                    <span class="font-mono text-ink/40">{{ $log->hours_spent }}h</span>
                </div>
            @endforeach
        </div>

        @if ($evaluation)
            <p class="text-xs uppercase tracking-widest text-ink/40 font-mono mb-4">Final evaluation</p>
            <div class="grid grid-cols-5 gap-3 mb-6">
                @foreach (\App\Models\Evaluation::CRITERIA as $key => $label)
                    <div class="text-center">
                        <p class="font-display text-lg font-semibold">{{ $evaluation->$key }}/5</p>
                        <p class="text-xs text-ink/50 mt-1">{{ $label }}</p>
                    </div>
                @endforeach
            </div>
            @if ($evaluation->comments)
                <p class="text-sm text-ink/70 italic border-l-2 border-accent pl-4">{{ $evaluation->comments }}</p>
            @endif
        @endif

        <div class="mt-12 pt-6 border-t border-line text-xs text-ink/30 font-mono">
            Generated by InternTrack on {{ now()->format('d M Y, h:i A') }}
        </div>
    </div>
@endsection
